spring:
  application:
    name: provider-service
  datasource:
    url: jdbc:mysql://localhost:3306/acmedb
    #url: jdbc:mysql://mysql-standalone:3306/acmedb
    username: acme
    password: acme123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dalect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    baselineOnMigrate: true
    baseline-version: 0
  devtools:
    remote.secret: thisismysecret
server:
  port: 9090